config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  delete "sign_out" => "sessions#destroy"
  get "/pages/*page" => "pages#show" , as: "page"  # *page -> [page] as an array
  # get "/pages/:page" => "pages#show"  # :page as a signle value
  get "list" => "pages#index"

  get 'community' => "home#community"
  
  resources :team
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :orders, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :trips, only: [:index, :show] do
      collection do
        get 'distance_by_day'
      end
    end
    collection do
      get :code
      get :nearby
      get :voucher
      get :personal
      get :setting
      get :admin
    end
  end
  resources :orders
  resources :stations
  resources :trips
  resources :bicycles
  resources :vouchers do
    resources :orders
    collection do
      get :instructions
      get :my_vouchers
    end
    member do
      get :redeem
      get :purchase
    end
  end

  get 'edit_credit_card' => "users#edit_credit_card"
  patch 'update_credit_card' => "users#update_credit_card"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
	belongs_to :station
	has_many :trips
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user, uniqueness: { scope: :voucher }
  belongs_to :user
  belongs_to :voucher
end

#user has 1 order which has many vouchers? vouchers can't be repeated

=begin
 create_table "orders", force: :cascade do |t|
    t.integer  "voucher_id"
    t.integer  "user_id"
    t.integer  "quantity"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_orders_on_user_id", using: :btree
    t.index ["voucher_id"], name: "index_orders_on_voucher_id", using: :btree
  end

=end

app/models/station.rb
class Station < ApplicationRecord
	has_many :bicycles
	validates :name, :latitude, :longitude, presence: true, uniqueness: { scope: [:latitude, :longitude] }

	geocoded_by :address  #if latLng values empty, based on address, automatically fills out latLng (latitude longitude) values
	after_validation :geocode, :if => :address_changed?
	#validates :latitude, uniqueness: { scope: :longitude }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def self.search(search, id)
		 where(['name LIKE ?', "%#{search}%"])
	end
	
end

app/models/team.rb
class Team < ApplicationRecord
	validates :name, uniqueness: true 
  has_many :users
  has_many :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user

    before_save :calculate_distance
    before_save :calculate_aircredit

    def calculate_distance
        self.distance = (Geocoder::Calculations.distance_between([start_latitude, start_longitude], [end_latitude, end_longitude])*1.61).round(2)
    end

    def calculate_aircredit
        self.air_credit_earned = self.distance * 15
    end

    def calculate_user_air_credit
        current_user.air_credit += self.air_credit_earned
    end # ** NEED TO DO SOMETHING TO AUTOMATICALLY UPDATE ATTR_ACCESSOR User.air_credit

    def distance_by_day
        result = Trip.group_by_day(:created_at).sum(:distance)
        render json: [{name: 'Distance Traveled', data: result}]
    end

end

=begin
  create_table "trips", force: :cascade do |t|
    t.float    "start_latitude"
    t.float    "start_longitude"
    t.float    "end_latitude"
    t.float    "end_longitude"
    t.datetime "started_at"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "bicycle_id"
    t.integer  "user_id"
    t.index ["bicycle_id"], name: "index_trips_on_bicycle_id", using: :btree
    t.index ["user_id"], name: "index_trips_on_user_id", using: :btree
  end
=end

app/models/user.rb
class User < ApplicationRecord

	before_save :default_values
	#attr_accessor :air_credit 

	has_secure_password
	has_many :teams
	has_many :orders
	has_many :vouchers, through: :orders
	has_many :trips

	def default_values
	  self.air_credit ||= 0
	end

end

app/models/voucher.rb
class Voucher < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user && session[:first_time] == nil
      session[:first_time] = false
      redirect_to page_path("scrolling-nav")
    end

    @trips = Trip.all
    @distance_traveled = Trip.all.group_by_day(:created_at).sum(:distance)
    @air_credits = Trip.all.group_by_day(:created_at).sum(:air_credit_earned)

    @leaderboard = User.joins(trips: :user).group(:email).sum(:distance).sort {|a,b| a[1] <=> b[1]}.reverse #makes array of user_id => distance [4, 10]... 
  end

  def community
  	@trips = Trip.all
  	@distance_traveled = Trip.all.group_by_day(:created_at).sum(:distance)
  	@air_credits = Trip.all.group_by_day(:created_at).sum(:air_credit_earned)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #require 'rqrcode'

  before_filter :authenticate_user, :only => [:code, :nearby, :voucher, :personal, :setting, :admin]
  before_filter :authenticate_admin, :only => [:admin]

  #below necessary?
  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      flash[:success] = "Registered successfully"
      redirect_to code_users_path
    else
      flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  def code
    @user = current_user
    @qr = RQRCode::QRCode.new(@user.email + @user.created_at.to_s, :size => 8, :level => :h )
  end

  def nearby
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      session[:user_id] = @user.id
      flash[:success] = "Account successfully updated"
      redirect_to :back
    else
      flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
      render 'edit'
    end
  end

  def edit_credit_card
    @user = current_user
  end

  def update_credit_card
    @user = current_user
    if @user.update(user_cc_params)
      flash[:success] = "Credit Card successfully updated"
      redirect_to setting_users_path
    else
      flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
      render 'edit_credit_card'
    end
  end

  def voucher
  end

  def personal
    @distance_by_day = Trip.where(user_id: current_user.id).group_by_day(:created_at).sum(:distance)
    @trips = Trip.where(user_id: current_user.id) 
    @air_credit_by_day = Trip.where(user_id: current_user.id).group_by_day(:created_at, format: "%m-%d").sum(:air_credit_earned)
    
  end

  def setting
    if current_user.credit_card = nil
      redirect_to edit_credit_card_path(id: @current_user.id)
    end
  end

  def admin
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end

  def user_cc_params
    params.require(:user).permit(:credit_card)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def svg(name)
		file_path = "airbike/app/assets/images/#{name}.svg"
		return File.read(file_path).html_safe if File.exists?(file_path)
		'(not found)'
	end
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/station_helper.rb
module StationHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trips_helper.rb
module TripsHelper

	def distance_by_day
		line_chart distance_by_day_user_trips_path, library: {
			title: {text: 'Distance by Day', x: -20},
			yAxis: {
				crosshair: true,
				title: {
					text: 'Distance Traveled'
				}
			},
			xAxis: {
				crosshair: true,
				title: {
					text: 'Day'
				}
			}
		}
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when 'success'
			"alert-success"
		when 'error'
			"alert-danger"
		else
			"alert-warning"
		end
	end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <%= image_tag user.avatar %>
  <div class="form-group">
    <%= f.label :avatar, 'Avatar URL' %>
    <%= f.text_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, 'Display Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'Email Address' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'New Password' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirm New Password' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit "Update Profile", class: 'btn btn-primary' %>
<% end %>

app/views/users/_form_cc.html.erb
<%= form_for user, url: update_credit_card_path, html: {method: "patch"} do |f| %>
  <div class="form-group">
    <%= f.label :credit_card, "Credit card number" %>
    <%= f.text_field :credit_card, class: 'form-control' %>
  </div>
  <div class="action_container">
    <%= f.submit "Update Credit Card Information", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/admin.html.erb
<h1 class="display-1">Administration</h1>
<hr>
<h1>Bicycle Management</h1>
<ul>
  <li><%= link_to "Show All", bicycles_path %></li>
  <li><%= link_to "Add New", new_bicycle_path %></li>
</ul>
<hr>
<h1>Station Management</h1>
<ul>
  <li><%= link_to "Show All", stations_path %></li>
  <li><%= link_to "Add New", new_station_path %></li>
</ul>
<hr>
<h1>Voucher Management</h1>
<ul>
  <!-- <li><%= link_to "Show All", vouchers_path %></li> -->
  <li><%= link_to "Add New", new_voucher_path %></li>
</ul>
<hr>
<h1>Trip Management</h1>
<ul>
  <li><%= link_to "Show All", trips_path %></li>
  <!-- <li><%= link_to "Add New", new_trip_path %></li> -->
</ul>

app/views/users/code.html.erb
<div class='row'>
  <div class='col-lg-8 offset-lg-2 center'>
    <h6>Please show the code to one of our security guards at AirBike Station</h5>
    <%=link_to 'Find a nearby station', nearby_users_path, class: 'btn btn-secondary' %>
  </div>
</div>
<h1 class='center'>AirBike Code</h1>
<div class='row'>
  <div class='col-lg-8 offset-lg-2'>
    <div class="card">
      <div class="card-block center">
        <img src=<%="https://chart.googleapis.com/chart?cht=qr&chs=300x300&chl=#{@user.email + @user.created_at.to_s}&choe=UTF-8"%> alt="QR code">
        <%= image_tag @user.avatar %>
      </div>
    </div>
  </div>
</div>
<div class='row'>
  <div class='col-lg-4 offset-lg-2'>
    <div class="card">
      <div class="card-block">
        <h4 class="card-title"> <%= @user.name %> </h4>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @user.email %> </li>
        <li class="list-group-item"><strong>Member since: </strong> <%= @user.created_at.strftime("%B %d, %Y") %> </li>
        <li class="list-group-item">What else goes here</li>
      </ul>
    </div>
  </div>
  <div class='col-lg-4'>
    <div class="card">
      <div class="card-block">
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: current_user %>

app/views/users/edit_credit_card.html.erb
<%= render 'form', user: current_user %>

app/views/users/nearby.html.erb
<h1>Nearby Stations</h1>
<div class='row'>
	<div class='col-lg-8 offset-lg-2'>
		<h5>Map</h5>
		<div id="map" style="height:400px;width:600px;"></div>

		<ul>
		  <li>Map</li>


		  <li>If you have any question, please call us at:</li>
		  <li>########</li>
		</ul>
	</div>
</div>
	<script>
	function initMap() {
	  var map = new google.maps.Map(document.getElementById('map'), {
	    center: {lat: 10.781915, lng: 106.69796},
	    zoom: 14
	  });
	  var locations = <%= raw Station.pluck(:name, :latitude, :longitude) %>;

	  var infoWindow = new google.maps.InfoWindow({map: map});

	  // Try HTML5 geolocation.
	  if (navigator.geolocation) {
	    navigator.geolocation.getCurrentPosition(function(position) {
	      var pos = {
	        lat: position.coords.latitude,
	        lng: position.coords.longitude
	      };

	      infoWindow.setPosition(pos);
	      infoWindow.setContent('You are here');
	      map.setCenter(pos);
	    }, function() {
	      handleLocationError(true, infoWindow, map.getCenter());
	    });
	  } else {
	    // Browser doesn't support Geolocation
	    handleLocationError(false, infoWindow, map.getCenter());
	  }

	  var marker, i;  

	  for (i = 0; i < locations.length; i++) {
	    marker = new google.maps.Marker({
	      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
	      //icon: icons.icon,
	      map: map

	      });

	    google.maps.event.addListener(marker, 'click', (function(marker, i) {
	      return function() {
	        infowindow.setContent(locations[i][0]);
	        infowindow.open(map, marker);
	      }
	    })(marker, i));
	  }
	  	// on click should have marker station but doesn't work
	  	// also needs to have an internal function of based on all locations of stations, filters out nearedst 3 - 4
	  	//also, can try to put custom marker

	  	/*  below is example of using distance calculation
var latitude1  = 39.46;
var longitude1 = -0.36;
var latitude2  = 40.40;
var longitude2 = -3.68;

var distance = google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(latitude1,longitude1), new google.maps.LatLng(latitude2,longitude2));  
	  	*/

	}

	function handleLocationError(browserHasGeolocation, infoWindow, pos) {
	  infoWindow.setPosition(pos);
	  infoWindow.setContent(browserHasGeolocation ?
	                        'Error: The Geolocation service failed.' :
	                        'Error: Your browser doesn\'t support geolocation.');
	}
	
 // should put filter by top 3 nearest stations based on distance. 

	/*function initMap() {
		var loc {};
		var geocoder = new google.maps.Geocoder();
		if (google.loader.ClientLocation) {
			loc.lat = google.loader.ClientLocation.latitude;
			loc.lng = google.loader.ClientLocation.longitude;

			var latlng = new google.maps.LatLng(loc.lat, loc.lng);
			geocoder.geocode({'latLng': latlng}, function(results, status) {
				if(status == google.maps.GeocoderStatus.OK) {
					alert(results[0]['formatted_address']);
				};
			});
		}
	} */

	/*
  var im = 'http://www.robotwoods.com/dev/misc/bluecircle.png';
  function locate(){
		navigator.geolocation.getCurrentPosition(initialize,fail);
  }

  function initMap() {
		var directionsDisplay = new google.maps.DirectionsRenderer;
		var directionsService = new google.maps.DirectionsService;
		var myLatLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

		var locations = <%= raw Station.pluck(:name, :latitude, :longitude) %>;



   var map = new google.maps.Map(document.getElementById('map'), {
     zoom: 14,
     center: myLatLng,
     mapTypeId: google.maps.MapTypeId.ROADMAP
   });

		var userMarker = new google.maps.Marker({
			position: myLatLng,
			map: map,
			icon: im
		});

   directionsDisplay.setMap(map);

   var infowindow = new google.maps.InfoWindow();

   var marker, i;  

   for (i = 0; i < locations.length; i++) {
     marker = new google.maps.Marker({
       position: new google.maps.LatLng(locations[i][1], locations[i][2]),
       map: map
       });

     google.maps.event.addListener(marker, 'click', (function(marker, i) {
       return function() {
         infowindow.setContent(locations[i][0]);
         infowindow.open(map, marker);
       }
     })(marker, i));

     google.maps.event.addListener(map, 'click', function(event) {
       placeMarker(map, event.latLng);
     });

     function placeMarker(map, location) {
       var marker = new google.maps.Marker({
         position: location,
         map: map
       });

       var infowindow = new google.maps.InfoWindow({
         content: 'Latitude: ' + location.lat() + '<br>Longitude: ' + location.lng()
       });

       infowindow.open(map,marker);  //need to put it into temporary array or something
     }


   }
 }*/


 /* going to put in givens
/*
 function calculateAndDisplayRoute(directionsService, directionsDisplay) {
   directionsService.route({
     origin: {lat: 10.781915, lng: 106.69796}, // Work
     destination: {lat: 10.780271, lng: 106.688098}, // Gym
     travelMode: 'WALKING'
   }, function(response, status) {
     if (status == 'OK') {
       directionsDisplay.setDirections(response);
     } else {
       window.alert('Directions request failed due to ' + status);
     }
   });
 } */
 
 </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwPKgwz5gKHp7lA1Ix1KK5Y95iQR3iR7c&callback=initMap"
    type="text/javascript"></script>

app/views/users/new.html.erb
<div class='row'>
	<div class='col-lg-4 offset-lg-8'>
		<div class='title'>
			<h1>Create An Account</h1>
		</div>
	</div>
</div>

<div class='row'>
	<div class='col-lg-8'>
		<%= image_tag'macbook.png', class: "resize" %>
	</div>
	<div class='col-lg-4'>
		<%= form_for @user do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, placeholder: "Enter your full name.", class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, placeholder: "Enter your email...", class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
		</div>

			<%= f.submit "Create Account", class: 'btn btn-secondary' %>
			<% end %> <br>

			<p>Already a user? <%= link_to "Sign In", new_session_path %></p>
		<form action="/users" method="post">
		</form>
	</div>
</div>

app/views/users/personal.html.erb
<div class="row">
  <div class ="col-lg-3">
  <div class ='title'>
    <h1>Personal Data</h1>
  </div>
    <%= link_to 'My Trips', user_trips_path(current_user.id) %> |
    <%= link_to 'Community Page', community_path %>
  </div>
<div class="col-lg-6">
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <h3>Distance biked (km) by day</h3> 
        </a>
      </h5>
    </div>
    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
    <p><strong>Total Distance: </strong> <h3><%= @trips.sum(:distance) %> kilometers </h3></p>

      <div class="card-block">
        <%= line_chart @distance_by_day %>
      </div>
    </div>

  </div>


  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Air Credit
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="card-block">
    <%= bar_chart @air_credit_by_day %>
      </div>
  <strong>Total Air Credit: </strong> <%= @trips.sum(:air_credit_earned) %> points

    </div>
  </div>
</div>




</div>
</div>

app/views/users/setting.html.erb
<h1 class="display-1">Personal</h1>
<p>In this page, you will</p>

<% if current_user %>
	<ul>
		<li><strong>Instructions: </strong></li>
		<img src="http://lorempixel.com/300/300/people/">
		<li><%= link_to "Update Avatar" %></li>
		<li>This goes to <%= link_to "code", code_users_path%></li>
		<li>Upon login, there should be a card display of all the vouchers</li>
	</ul>
	  <%= link_to "Change Password", edit_user_path(id: @current_user.id) %> |
	  <%= link_to "Update Credit Card Information", edit_credit_card_path(id: @current_user.id) %> | <%= link_to "Sign out", sign_out_path, method: 'delete' %>
<% else %>
	  <li><%= link_to "Sign up", new_user_path, method: 'delete' %></li>
<% end %>

<h1 class="display-1">Account settings</h1>
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Account
        </a>
      </h5>
    </div>
    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-block">
        <p>To view your account info as AirBike Card to show up at Bike Stations, follow Menu -> Code or click this quick <%= link_to "link", code_users_path%> </p>
        <hr>
        <%= render 'form', user: current_user %>
        <hr>
        <%= link_to "Sign out", sign_out_path, method: 'delete', class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Payment
        </a>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="card-block">
        <%= render 'form_cc', user: current_user %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Instruction
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="card-block">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>