config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  delete "sign_out" => "sessions#destroy"
  get "/pages/*page" => "pages#show" , as: "page"  # *page -> [page] as an array
  # get "/pages/:page" => "pages#show"  # :page as a signle value
  get "list" => "pages#index"

  get 'community' => "home#community"
  
  resources :team
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :orders, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :trips, only: [:index, :show] do
      collection do
        get 'distance_by_day'
      end
    end
    collection do
      get :code
      get :nearby
      get :voucher
      get :personal
      get :setting
      get :admin
    end
  end
  resources :orders
  resources :stations
  resources :trips
  resources :bicycles
  resources :vouchers do
    resources :orders
    collection do
      get :instructions
      get :my_vouchers
    end
    member do
      get :redeem
      get :purchase
    end
  end

  get 'edit_credit_card' => "users#edit_credit_card"
  patch 'update_credit_card' => "users#update_credit_card"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
	belongs_to :station
	has_many :trips
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user, uniqueness: { scope: :voucher }
  belongs_to :user
  belongs_to :voucher
end

#user has 1 order which has many vouchers? vouchers can't be repeated

=begin
 create_table "orders", force: :cascade do |t|
    t.integer  "voucher_id"
    t.integer  "user_id"
    t.integer  "quantity"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_orders_on_user_id", using: :btree
    t.index ["voucher_id"], name: "index_orders_on_voucher_id", using: :btree
  end

=end

app/models/station.rb
class Station < ApplicationRecord
	has_many :bicycles
	validates :name, :latitude, :longitude, presence: true, uniqueness: { scope: [:latitude, :longitude] }

	geocoded_by :address  #if latLng values empty, based on address, automatically fills out latLng (latitude longitude) values
	after_validation :geocode, :if => :address_changed?
	#validates :latitude, uniqueness: { scope: :longitude }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def self.search(search, id)
		 where(['name LIKE ?', "%#{search}%"])
	end
	
end

app/models/team.rb
class Team < ApplicationRecord
	validates :name, uniqueness: true 
  has_many :users
  has_many :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user

    before_save :calculate_distance
    before_save :calculate_aircredit

    def calculate_distance
        self.distance = (Geocoder::Calculations.distance_between([start_latitude, start_longitude], [end_latitude, end_longitude])*1.61).round(2)
    end

    def calculate_aircredit
        self.air_credit_earned = self.distance * 15
    end

    def calculate_user_air_credit
        current_user.air_credit += self.air_credit_earned
    end # ** NEED TO DO SOMETHING TO AUTOMATICALLY UPDATE ATTR_ACCESSOR User.air_credit

    def distance_by_day
        result = Trip.group_by_day(:created_at).sum(:distance)
        render json: [{name: 'Distance Traveled', data: result}]
    end

end

=begin
  create_table "trips", force: :cascade do |t|
    t.float    "start_latitude"
    t.float    "start_longitude"
    t.float    "end_latitude"
    t.float    "end_longitude"
    t.datetime "started_at"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "bicycle_id"
    t.integer  "user_id"
    t.index ["bicycle_id"], name: "index_trips_on_bicycle_id", using: :btree
    t.index ["user_id"], name: "index_trips_on_user_id", using: :btree
  end
=end

app/models/user.rb
class User < ApplicationRecord

	before_save :default_values
	#attr_accessor :air_credit 

	has_secure_password
	has_many :teams
	has_many :orders
	has_many :vouchers, through: :orders
	has_many :trips

	def default_values
	  self.air_credit ||= 0
	end

end

app/models/voucher.rb
class Voucher < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user && session[:first_time] == nil
      session[:first_time] = false
      redirect_to page_path("scrolling-nav")
    end

    @trips = Trip.all
    @distance_traveled = Trip.all.group_by_day(:created_at).sum(:distance)
    @air_credits = Trip.all.group_by_day(:created_at).sum(:air_credit_earned)

    @leaderboard = User.joins(trips: :user).group(:email).sum(:distance).sort {|a,b| a[1] <=> b[1]}.reverse #makes array of user_id => distance [4, 10]... 
  end

  def community
  	@trips = Trip.all
  	@distance_traveled = Trip.all.group_by_day(:created_at).sum(:distance)
  	@air_credits = Trip.all.group_by_day(:created_at).sum(:air_credit_earned)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
	before_action :set_station, only: [:show, :edit, :update, :destroy]

	def index
		if params[:search].present?
		  @stations = Station.search(params[:search], :order => :distance)
		else
		  @stations = Station.all.order('name')
		end
	end

	def show
	end


	def new
		@station = Station.new
	end

	def create
		@station = Station.create station_params
		if @station.persisted?
			flash[:success] = "Station created successfully"
			redirect_to stations_path
		else
			flash.now[:error] = "Error: #{@station.errors.full_messages.to_sentence}"
			render 'new'
		end
	end

	def destroy
		@station.destroy
		respond_to do |format|
		  format.html { redirect_to stations_url, notice: 'Location was successfully destroyed.' }
		  format.json { head :no_content }
		end
	end

	def edit
	end

	def update
		respond_to do |format|
		  if @station.update(station_params)
		    format.html { redirect_to @station, notice: 'Location was successfully updated.' }
		    format.json { render :show, status: :ok, station: @station }
		  else
		    format.html { render :edit }
		    format.json { render json: @station.errors, status: :unprocessable_entity }
		  end
		end
	end



	private

	def set_station
		@station = Station.find(params[:id])
	end

	def station_params
		params.require(:station).permit(:name, :address, :latitude, :longitude)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def svg(name)
		file_path = "airbike/app/assets/images/#{name}.svg"
		return File.read(file_path).html_safe if File.exists?(file_path)
		'(not found)'
	end
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/station_helper.rb
module StationHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trips_helper.rb
module TripsHelper

	def distance_by_day
		line_chart distance_by_day_user_trips_path, library: {
			title: {text: 'Distance by Day', x: -20},
			yAxis: {
				crosshair: true,
				title: {
					text: 'Distance Traveled'
				}
			},
			xAxis: {
				crosshair: true,
				title: {
					text: 'Day'
				}
			}
		}
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when 'success'
			"alert-success"
		when 'error'
			"alert-danger"
		else
			"alert-warning"
		end
	end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/station/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<%= form_tag stations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.address %></td>
        <td><%= station.latitude %></td>
        <td><%= station.longitude %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %> | 
<%= link_to 'Trips', trips_path %>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<h3>Map of all our Stations</h3>

<div id="map" style="width:700px;height:500px"></div>


<%= form_tag stations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.address %></td>
        <td><%= station.latitude %></td>
        <td><%= station.longitude %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <script>
  function initMap() {
    var directionsDisplay = new google.maps.DirectionsRenderer;
    var directionsService = new google.maps.DirectionsService;

    var locations = <%= raw Station.pluck(:name, :latitude, :longitude) %>;

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: new google.maps.LatLng(10.774937, 106.686988),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var iconBase = '/app/images/'
    var icons = {
      station: {
        icon: iconBase + 'bike_station.png'
      }
    };

      var infoWindow = new google.maps.InfoWindow({map: map});

      // Try HTML5 geolocation.
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };

          infoWindow.setPosition(pos);
          infoWindow.setContent('You are here');
          map.setCenter(pos);
        }, function() {
          handleLocationError(true, infoWindow, map.getCenter());
        });
      } else {
        // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
      }

    directionsDisplay.setMap(map);

    var infowindow = new google.maps.InfoWindow();



    var marker, i;  

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        icon: icons.icon,
        map: map

        });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));

      google.maps.event.addListener(map, 'click', function(event) {
        placeMarker(map, event.latLng);
      });

      function placeMarker(map, location) {
        var marker = new google.maps.Marker({
          position: location,
          map: map
        });

        var infowindow = new google.maps.InfoWindow({
          content: 'Latitude: ' + location.lat() + '<br>Longitude: ' + location.lng()
        });

        infowindow.open(map,marker);  //need to put it into temporary array or something
      }


    }
  }
  /* going to put in givens
 /*
  function calculateAndDisplayRoute(directionsService, directionsDisplay) {
    directionsService.route({
      origin: {lat: 10.781915, lng: 106.69796}, // Work
      destination: {lat: 10.780271, lng: 106.688098}, // Gym
      travelMode: 'WALKING'
    }, function(response, status) {
      if (status == 'OK') {
        directionsDisplay.setDirections(response);
      } else {
        window.alert('Directions request failed due to ' + status);
      }
    });
  } */
  
  </script>



<br>

<%= link_to 'New Station', new_station_path %> | 
<%= link_to 'Trips', trips_path %>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwPKgwz5gKHp7lA1Ix1KK5Y95iQR3iR7c&callback=initMap"
type="text/javascript"></script>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

<%# put in _station.json.jbuilder: json.extract! location, :id, :address, :latitude, :longitude, :created_at, :updated_at
json.url location_url(location, format: :json) %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Name: </strong>
	<%= @station.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @station.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @station.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @station.longitude %>
</p>

<div id="map" style="width:450px;height:300px"></div>

<%#<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@station.latitude}%2C#{@station.longitude}" %>

<h3>Nearby Bike Stations</h3>
<ul>
<% for station in @station.nearbys(3) %>
  <li><%= link_to station.name, station %> (<%= station.distance.round(2) %> miles)</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

<script>
      function initMap() {
        var uluru = {lat: <%= @station.latitude %>, lng: <%= @station.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
          //icon: '/images/bike_station.png'
        });

        marker.setMap(map); 

        google.maps.event.addListener(marker,'click',function() {

          map.setZoom(18);
          map.setCenter(marker.getPosition());
          /*var infowindow = new google.maps.InfoWindow({
            content: <%= @station.name %>
          });
          infowindow.open(map,marker);*/
        
        });

      }
    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwPKgwz5gKHp7lA1Ix1KK5Y95iQR3iR7c&callback=initMap"
    type="text/javascript"></script>

<%# put in show.json.jbuilder: json.partial! "stations/station", station: @station %>