config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  delete "sign_out" => "sessions#destroy"
  get "/pages/*page" => "pages#show" , as: "page"  # *page -> [page] as an array
  # get "/pages/:page" => "pages#show"  # :page as a signle value
  get "list" => "pages#index"

  get 'community' => "home#community"
  
  resources :team
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :orders, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :trips, only: [:index, :show] do
      collection do
        get 'distance_by_day'
      end
    end
    collection do
      get :code
      get :nearby
      get :voucher
      get :personal
      get :setting
      get :admin
    end
  end
  resources :orders
  resources :stations
  resources :trips
  resources :bicycles
  resources :vouchers do
    resources :orders
    collection do
      get :instructions
      get :my_vouchers
    end
    member do
      get :redeem
      get :purchase
    end
  end

  get 'edit_credit_card' => "users#edit_credit_card"
  patch 'update_credit_card' => "users#update_credit_card"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
	belongs_to :station
	has_many :trips
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user, uniqueness: { scope: :voucher }
  belongs_to :user
  belongs_to :voucher
end

#user has 1 order which has many vouchers? vouchers can't be repeated

=begin
 create_table "orders", force: :cascade do |t|
    t.integer  "voucher_id"
    t.integer  "user_id"
    t.integer  "quantity"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_orders_on_user_id", using: :btree
    t.index ["voucher_id"], name: "index_orders_on_voucher_id", using: :btree
  end

=end

app/models/station.rb
class Station < ApplicationRecord
	has_many :bicycles
	validates :name, :latitude, :longitude, presence: true, uniqueness: { scope: [:latitude, :longitude] }

	geocoded_by :address  #if latLng values empty, based on address, automatically fills out latLng (latitude longitude) values
	after_validation :geocode, :if => :address_changed?
	#validates :latitude, uniqueness: { scope: :longitude }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def self.search(search, id)
		 where(['name LIKE ?', "%#{search}%"])
	end
	
end

app/models/team.rb
class Team < ApplicationRecord
	validates :name, uniqueness: true 
  has_many :users
  has_many :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user

    before_save :calculate_distance
    before_save :calculate_aircredit

    def calculate_distance
        self.distance = (Geocoder::Calculations.distance_between([start_latitude, start_longitude], [end_latitude, end_longitude])*1.61).round(2)
    end

    def calculate_aircredit
        self.air_credit_earned = self.distance * 15
    end

    def calculate_user_air_credit
        current_user.air_credit += self.air_credit_earned
    end # ** NEED TO DO SOMETHING TO AUTOMATICALLY UPDATE ATTR_ACCESSOR User.air_credit

    def distance_by_day
        result = Trip.group_by_day(:created_at).sum(:distance)
        render json: [{name: 'Distance Traveled', data: result}]
    end

end

=begin
  create_table "trips", force: :cascade do |t|
    t.float    "start_latitude"
    t.float    "start_longitude"
    t.float    "end_latitude"
    t.float    "end_longitude"
    t.datetime "started_at"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "bicycle_id"
    t.integer  "user_id"
    t.index ["bicycle_id"], name: "index_trips_on_bicycle_id", using: :btree
    t.index ["user_id"], name: "index_trips_on_user_id", using: :btree
  end
=end

app/models/user.rb
class User < ApplicationRecord

	before_save :default_values
	#attr_accessor :air_credit 

	has_secure_password
	has_many :teams
	has_many :orders
	has_many :vouchers, through: :orders
	has_many :trips

	def default_values
	  self.air_credit ||= 0
	end

end

app/models/voucher.rb
class Voucher < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/station_helper.rb
module StationHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trips_helper.rb
module TripsHelper

	def distance_by_day
		line_chart distance_by_day_user_trips_path, library: {
			title: {text: 'Distance by Day', x: -20},
			yAxis: {
				crosshair: true,
				title: {
					text: 'Distance Traveled'
				}
			},
			xAxis: {
				crosshair: true,
				title: {
					text: 'Day'
				}
			}
		}
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when 'success'
			"alert-success"
		when 'error'
			"alert-danger"
		else
			"alert-warning"
		end
	end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Simple Sidebar - Start Bootstrap Template</title>
    <link href="/assets/stylesheets/simple-sidebar/simple-sidebar.css" rel="stylesheet">
  </head>
  <body>
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <div class="alert <%= flash_class_name(key) %>" >
          <%= value %>
        </div>
      <% end %>
    <% end %>
    <% if current_user %>
      <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
          <ul class="date-wrapper">
            <li class="day">
              <a>
                <%= image_tag 'airbike_white_logo_white_type.svg', class: "logo-size" %>
              </a>
              <%= today_day %>
            </li>
            <li class="month">
              <%= today_month %>
            </li>
          </ul>
          <ul class="personal-wrapper">
            <li class="name">
              Hi <%= current_user.name %>
            </li>
            <span class="line"></span>
            <% if current_user.air_credit = 0 %>
              <li class="air-credit">
                You currently have <%= current_user.air_credit %> AirCredit </br>
              <%= link_to 'To earn AirCredit, you need to rent an AirBike', instructions_vouchers_path, class: "zero-aircredit"%>
            </li>
          <% else %>
            <li class="air-credit">
              You currently have <%= current_user.air_credit %> AirCredit
          </li>
          <% end %>
        </ul>
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
          </li>
          <li class='nav-item'>
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
          <li class='nav-item'>
            <%= link_to "Access Code", code_users_path, class: "nav-link" %>
          </li>
          <li class='nav-item'>
            <%= link_to "Personal Data", personal_users_path, class: "nav-link" %>
          </li>
          <li class='nav-item'>
            <%= link_to "My Vouchers", orders_path , class: "nav-link" %>
          </li>
          <li class='nav-item'>
            <%= link_to "Vouchers", vouchers_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Log Out", new_session_path, method: 'delete', class: "dropdown-item black" %>
          </li>
          <li class="nav-item dropdown float-xs-right">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <%= link_to "My Account", setting_users_path, class: "dropdown-item black" %>
              <%= link_to "Instructions", instructions_vouchers_path, class: "dropdown-item black" %>
              <%= link_to "Log Out", sign_out_path, method: 'delete', class: "dropdown-item black" %>
            </div>
          </li>
        </ul>
      </div>
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-10 offset-lg-2">
              <div class='container'>
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
  <% else %>
    <div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="date-wrapper">
          <li class="day">
            <a>
              <%= image_tag 'airbike_white_logo_white_type.svg', class: "logo-size" %>
            </ul>
            <ul class="sidebar-nav">
              <li>
                <%= link_to "Sign In", new_session_path, class: "nav-link" %>
              </li>
              <li>
                <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
          <div id="page-content-wrapper">
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-10 offset-lg-2">
                  <div class='container'>
                    <%= yield %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- /#page-content-wrapper -->
        </div>
      <% end %>
    </script>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
	<head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/pages/scrolling-nav.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Scrolling Nav - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <!--     <link href="/assets/stylesheets/scrolling-nav/bootstrap.min.css" rel="stylesheet"> -->
    <!-- Custom CSS -->
    <link href="/assets/stylesheets/scrolling-nav/scrolling-nav.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <section id="intro" class="intro-section">
      <div class="container">
        <!-- <div class="row">
          <div class="col-lg-12">
            <h1>Change The World</br> One Cycle at a Time</h1>
          <a class="btn btn-default page-scroll" href="#about">Continue</a>
        </div>
      </div> -->
        <!-- logo row -->
        <div class="row">
          <div class="col-xs-1"></div>
          <div class="col-xs-2">
            <%= image_tag 'airbike_logo_white_type.svg' %>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
          <div class="col-xs-1"></div>
        </div>
        <!-- slogan row -->
        <div id="slogan_row" class="row">
          <div class="col-xs-5"></div>
          <div class="col-xs-5 change-the-world">Change the world</div>
          <div class="col-xs-2"></div>
        </div>
        <!-- line row -->
        <div class="row">
          <div class="col-xs-5"></div>
          <div class="col-xs-5">
            <hr class="line">
          </div>
          <div class="col-xs-2"></div>
        </div>
        <!-- some texts row -->
        <div class="row">
          <div class="col-xs-1"></div>
          <div class="col-xs-4 new_cycler">3,205,943 new cyclers</div>
          <div class="col-xs-2"></div>
          <div class="col-xs-3 one-cycle-at-a-time">one cycle at a time</div>
          <div class="col-xs-2"></div>
        </div>
        <!-- down arrow -->
        <a href="#about" class="page-scroll">
          <%= image_tag 'down_arrow.svg', id: "down_arrow" %>
        </a>
      </div>
    </section>
  </div>
  <!-- About Section -->
  <section id="about" class="about-section">
    <!-- <div class="container">
    </div> -->
    <div class="row">
      <div class="col-xs-4 ">
        <div></div>
        <%= image_tag 'motorbike.jpg', id: "motobike" %>
      </div>
      <div class="col-xs-4 purpose">
        <p class="change-the-world">Purpose</p>
        <hr class="line2">
        <p class="purpose_description">Our mission is to bring clean air to Vietnam. There are many factors to air pollution but the obvious one is the high volume of motobicycles. There are over 7.4 millions motorcyles in Hanoi. Working together, we can create a better environment not for ourselves but for the future generations.</p>
      </div>
      <div class="col-xs-4">
        <%= image_tag 'bike.jpg', id: "bicycle" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5"></div>
      <div class="col-xs-3 ">
        <a id="down_link" href="#contact" class="page-scroll change-the-world">How To Start</a>
      </div>
      <div class="col-xs-4"></div>
    </div>
  </section>
  <!-- Contact Section -->
  <section id="contact" class="contact-section">
    <div class="container">
      <div class="row">
        <!-- <div class="col-lg-12">
          <h1>Reward yourself</h1>
          <p>Use your AirCredit to buy food, clothes vouchers and much more.</p>
          <p>You earn this, you deserve it, enjoy it.</p>
          <p>Are you ready to earn your reward by riding with us? What are you waiting for? Click below button</p>
          <a class="btn btn-default page-scroll" href="<%= new_user_path %>">Sign Up</a>
        </div> -->
        <div class="col-xs-4">
          <%= image_tag 'bicycle_icon_select.png', class: "step_icon" %>
        </div>
        <div class="col-xs-4">
          <%= image_tag 'aircredit_icon_select.png', class: "step_icon" %>
        </div>
        <div class="col-xs-4">
          <%= image_tag 'reward_icon_select.png', class: "step_icon" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 grab-an-airBike">Grab an AirBike</div>
        <div class="col-xs-4 grab-an-airBike">Earn AirCredit</div>
        <div class="col-xs-4 grab-an-airBike">Reward Yourself</div>
      </div>
      <div class="row">
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
          <p class="how_to_description">Visit one of our stations and we’ll help you get started with your airbike. Make sure you have a credit card for security purposes</p>
        </div>
        <div class="col-xs-4"></div>
      </div>
      <div id="signup_row" class="row">
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
          <a class="signup" href="<%= new_user_path %>">Sign Up</a>
        </div>
        <div class="col-xs-4"></div>
      </div>
    </div>
  </section>
  <!-- jQuery -->
  <script src="/assets/javascripts/scrolling-nav/jquery.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src="/assets/javascripts/scrolling-nav/bootstrap.min.js"></script>
  <!-- Scrolling Nav JavaScript -->
  <script src="/assets/javascripts/scrolling-nav/jquery.easing.min.js"></script>
  <script src="/assets/javascripts/scrolling-nav/scrolling-nav.js"></script>
</body>
</html>

app/views/pages/simple-sidebar.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Simple Sidebar - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="/assets/stylesheets/simple-sidebar/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/assets/stylesheets/simple-sidebar/simple-sidebar.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <a href="#">
              Start Bootstrap
                    </a>
          </li>
          <li>
            <a href="#">Dashboard</a>
          </li>
          <li>
            <a href="#">Shortcuts</a>
          </li>
          <li>
            <a href="#">Overview</a>
          </li>
          <li>
            <a href="#">Events</a>
          </li>
          <li>
            <a href="#">About</a>
          </li>
          <li>
            <a href="#">Services</a>
          </li>
          <li>
            <a href="#">Contact</a>
          </li>
        </ul>
      </div>
      <!-- /#sidebar-wrapper -->
      <!-- Page Content -->
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <h1>Simple Sidebar</h1>
              <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
              <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
              <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
            </div>
          </div>
        </div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="/assets/javascripts/simple-sidebar/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/javascripts/simple-sidebar/bootstrap.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
  </body>
</html>