config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  delete "sign_out" => "sessions#destroy"
  get "/pages/*page" => "pages#show" , as: "page"  # *page -> [page] as an array
  # get "/pages/:page" => "pages#show"  # :page as a signle value
  get "list" => "pages#index"

  get 'community' => "home#community"
  
  resources :team
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :orders, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :trips, only: [:index, :show] do
      collection do
        get 'distance_by_day'
      end
    end
    collection do
      get :code
      get :nearby
      get :voucher
      get :personal
      get :setting
      get :admin
    end
  end
  resources :orders
  resources :stations
  resources :trips
  resources :bicycles
  resources :vouchers do
    resources :orders
    collection do
      get :instructions
      get :my_vouchers
    end
    member do
      get :redeem
      get :purchase
    end
  end

  get 'edit_credit_card' => "users#edit_credit_card"
  patch 'update_credit_card' => "users#update_credit_card"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
	belongs_to :station
	has_many :trips
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user, uniqueness: { scope: :voucher }
  belongs_to :user
  belongs_to :voucher
end

#user has 1 order which has many vouchers? vouchers can't be repeated

=begin
 create_table "orders", force: :cascade do |t|
    t.integer  "voucher_id"
    t.integer  "user_id"
    t.integer  "quantity"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_orders_on_user_id", using: :btree
    t.index ["voucher_id"], name: "index_orders_on_voucher_id", using: :btree
  end

=end

app/models/station.rb
class Station < ApplicationRecord
	has_many :bicycles
	validates :name, :latitude, :longitude, presence: true, uniqueness: { scope: [:latitude, :longitude] }

	geocoded_by :address  #if latLng values empty, based on address, automatically fills out latLng (latitude longitude) values
	after_validation :geocode, :if => :address_changed?
	#validates :latitude, uniqueness: { scope: :longitude }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def self.search(search, id)
		 where(['name LIKE ?', "%#{search}%"])
	end
	
end

app/models/team.rb
class Team < ApplicationRecord
	validates :name, uniqueness: true 
  has_many :users
  has_many :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user

    before_save :calculate_distance
    before_save :calculate_aircredit

    def calculate_distance
        self.distance = (Geocoder::Calculations.distance_between([start_latitude, start_longitude], [end_latitude, end_longitude])*1.61).round(2)
    end

    def calculate_aircredit
        self.air_credit_earned = self.distance * 15
    end

    def calculate_user_air_credit
        current_user.air_credit += self.air_credit_earned
    end # ** NEED TO DO SOMETHING TO AUTOMATICALLY UPDATE ATTR_ACCESSOR User.air_credit

    def distance_by_day
        result = Trip.group_by_day(:created_at).sum(:distance)
        render json: [{name: 'Distance Traveled', data: result}]
    end

end

=begin
  create_table "trips", force: :cascade do |t|
    t.float    "start_latitude"
    t.float    "start_longitude"
    t.float    "end_latitude"
    t.float    "end_longitude"
    t.datetime "started_at"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "bicycle_id"
    t.integer  "user_id"
    t.index ["bicycle_id"], name: "index_trips_on_bicycle_id", using: :btree
    t.index ["user_id"], name: "index_trips_on_user_id", using: :btree
  end
=end

app/models/user.rb
class User < ApplicationRecord

	before_save :default_values
	#attr_accessor :air_credit 

	has_secure_password
	has_many :teams
	has_many :orders
	has_many :vouchers, through: :orders
	has_many :trips

	def default_values
	  self.air_credit ||= 0
	end

end

app/models/voucher.rb
class Voucher < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user && session[:first_time] == nil
      session[:first_time] = false
      redirect_to page_path("scrolling-nav")
    end

    @trips = Trip.all
    @distance_traveled = Trip.all.group_by_day(:created_at).sum(:distance)
    @air_credits = Trip.all.group_by_day(:created_at).sum(:air_credit_earned)

    @leaderboard = User.joins(trips: :user).group(:email).sum(:distance).sort {|a,b| a[1] <=> b[1]}.reverse #makes array of user_id => distance [4, 10]... 
  end

  def community
  	@trips = Trip.all
  	@distance_traveled = Trip.all.group_by_day(:created_at).sum(:distance)
  	@air_credits = Trip.all.group_by_day(:created_at).sum(:air_credit_earned)
  end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  before_action :set_voucher, only: [:show, :edit, :update, :destroy]

  def index
    @vouchers = Voucher.all.order(created_at: :desc)
    # if Order.where(user_id: current_user.id).exists?(['voucher_id ILIKE ?', '%#{@vouchers.map(&:id)}%'])
    #   flash.now[:error] = "You can't have more than the same voucher"
    #   redirect_to vouchers_path
    # end
  end

  def new
    @voucher = Voucher.new
  end

  def redeem
    @voucher = Voucher.find(params[:id])
  end

  def purchase
    @voucher = Voucher.find(params[:id])
  end

  def my_voucher
  end

  def instructions
  end

  def list
    @vouchers = Voucher.all.order(created_at: :desc)
  end

  def show
  end

  def create
    @voucher = Voucher.create voucher_params
    # TODO: NEED TO REMOVE THIS LATER
    @voucher.expired_at = Date.today + 60.days
    @voucher.save!
    if @voucher.persisted?
      flash[:success] = "Voucher created successfully"
      redirect_to vouchers_path
    else
      flash.now[:error] = "Error: #{@voucher.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  def update
    if @voucher.update(voucher_params)
      redirect_to @voucher, notice: 'Voucher was successfully updated.'
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @voucher.destroy
    redirect_to vouchers_path, notice: 'Voucher was successfully destroyed.'
  end

  private

  def set_voucher
    @voucher = Voucher.find(params[:id])
  end

  def voucher_params
    params.require(:voucher).permit(:name, :voucher_type, :quantity, :discount_info, :aircredit_price, :description, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def svg(name)
		file_path = "airbike/app/assets/images/#{name}.svg"
		return File.read(file_path).html_safe if File.exists?(file_path)
		'(not found)'
	end
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/station_helper.rb
module StationHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trips_helper.rb
module TripsHelper

	def distance_by_day
		line_chart distance_by_day_user_trips_path, library: {
			title: {text: 'Distance by Day', x: -20},
			yAxis: {
				crosshair: true,
				title: {
					text: 'Distance Traveled'
				}
			},
			xAxis: {
				crosshair: true,
				title: {
					text: 'Day'
				}
			}
		}
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when 'success'
			"alert-success"
		when 'error'
			"alert-danger"
		else
			"alert-warning"
		end
	end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/vouchers/_form.html.erb
<%= form_for(voucher) do |f| %>
  <% if voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voucher.errors.count, "error") %> prohibited this station from being saved:</h2>
      <ul>
        <% voucher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :voucher_type %>
      <%= f.text_field :voucher_type, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :discount_info %>
      <%= f.number_field :discount_info, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :aircredit_price %>
      <%= f.number_field :aircredit_price, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :expired_at %> (for now this doesn't work yet T__T)
      <%= f.text_field :expired_at, "data-provide" => 'datepicker', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :status %>
      <%= f.text_field :status, class: 'form-control' %>
    </div>
  </div>
  <%= f.button 'Submit', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/vouchers/_vouchers.html.erb
<% voucher.each do |t| %>
<div class="col-lg-4 col-sm-6">
<h4 class="card-title-voucher"><%= t.name %></h4>
<div class="card">
    <ul class ="voucher-wrapper">
        <li><%= t.voucher_type %></li>
        <li>Total vouchers <%= t.quantity%></li>
        <li>AirCredit: <%= t.aircredit_price %></li>
        <li><%= t.discount_info %></li>
        <li><%= t.description %></li>    
        <li>Expires on <%= t.expired_at.strftime("%b %d") %></li>
        <div class="center">
           <%= link_to 'Redeem', new_voucher_order_path(t), class: 'btn btn-primary' %>
        </div>
    </ul>
</div>
</div>
<% end %>

app/views/vouchers/edit.html.erb
<h1>Editing Voucher <%= @voucher.name %></h1>
<%= link_to 'Show', @voucher %> | <%= link_to 'Back', vouchers_path %>
<hr>
<%= render 'form', voucher: @voucher %>

app/views/vouchers/index.html.erb
<% if current_user %>
<% else %>
<% end %>
<div class='row'>
	<%= render partial: "vouchers", locals: {voucher: @vouchers}%>
</div>

app/views/vouchers/instructions.html.erb
<strong>Step 1</strong>
<p>
You will need to sign up an account to keep a history of your AirCredits!
</p>
<strong>Step 2</strong>
<p>
Once you have signed up, take your unique QR code to our security guard at one of our stations for security purposes. 
</p>
<strong>Step 3</strong>
<p>
Enjoy riding our AirBikes for two hours! Every 30 minutes after 2 hours will cost 1000 dong.
</p>
<%= link_to "Back To Vouchers", vouchers_path, class: 'btn btn-primary' %>

app/views/vouchers/list.html.erb
<p id="notice"><%= notice %></p>
<h1>Vouchers</h1>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Quantity</th>
      <th>%Off</th>
      <th>Expired at</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td><%= voucher.name %></td>
        <td><%= voucher.voucher_type %></td>
        <td><%= voucher.quantity %></td>
        <td><%= voucher.discount_info %></td>
        <td><%= voucher.expired_at.strftime("%d %b  %Y at %I:%M%p") %></td>
        <td><%= link_to 'Show', voucher %></td>
        <td><%= link_to 'Edit', edit_voucher_path(voucher) %></td>
        <td><%= link_to 'Destroy', voucher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Add Voucher', new_voucher_path %>

app/views/vouchers/my_vouchers.html.erb
<% unless @vouchers.any? %>
	<p class='center'> You don't have any vouchers in your inventory. Please redeem a voucher to see it on your list</p>
<% end %>

app/views/vouchers/new.html.erb
<h1>Add new Voucher</h1>
<%= link_to 'Back', vouchers_path %>
<hr>
<%= render 'form', voucher: @voucher %>

app/views/vouchers/redeem.html.erb
<%= @voucher.name %>

app/views/vouchers/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Detail of voucher <%= @voucher.name %></h1>
<p>
  <strong>Name: </strong>
  <%= @voucher.name %>
</p>
<p>
  <strong>Type: </strong>
  <%= @voucher.voucher_type %>
</p>
<p>
  <strong>Quantity: </strong>
  <%= @voucher.quantity %>
</p>
<p>
  <strong>%Off: </strong>
  <%= @voucher.discount_info %>
</p>
<p>
  <strong>AirCredit Price: </strong>
  <%= @voucher.aircredit_price %>
</p>
<p>
  <strong>Expired at: </strong>
  <%= @voucher.expired_at.strftime("%d %b  %Y at %I:%M%p") %>
</p>
<p>
  <strong>Description: </strong>
  <%= @voucher.description %>
</p>
<p>
  <strong>Status: </strong>
  <%= @voucher.status %>
</p>
<%= link_to 'Edit', edit_voucher_path(@voucher) %> | <%= link_to 'Back', vouchers_path %>